{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7bd86690",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append('../src/')\n",
    "from TWIG_utils import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2ea8785a",
   "metadata": {},
   "outputs": [],
   "source": [
    "stock_list = ['AMZN', 'TSLA', 'SNAP', 'INTC', 'PINS', 'SOFI', 'APPLE', 'F', 'BAC', 'T', 'GOOGL']\n",
    "date_start = '2022-01-01'\n",
    "date_end = '2023-04-28'\n",
    "\n",
    "client = RESTClient(auth_key=\"JeeOjlOPBe5aTiQ_Jb39raRqlam45uAO\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cc8448a0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting data pull for AMZN...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-29 12:24:24,347\tINFO services.py:1247 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m 2023-04-29 12:24:26,022\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m 2023-04-29 12:24:26,008\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m 2023-04-29 12:24:26,005\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m 2023-04-29 12:24:26,007\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m 2023-04-29 12:24:26,004\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m 2023-04-29 12:24:26,005\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m 2023-04-29 12:24:26,004\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m 2023-04-29 12:24:26,008\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m 2023-04-29 12:24:26,610\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m 2023-04-29 12:24:26,612\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m 2023-04-29 12:24:26,614\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18919)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m 2023-04-29 12:24:26,598\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m 2023-04-29 12:24:26,601\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m 2023-04-29 12:24:26,603\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18915)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m 2023-04-29 12:24:26,575\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m 2023-04-29 12:24:26,578\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m 2023-04-29 12:24:26,580\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18920)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m 2023-04-29 12:24:26,600\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m 2023-04-29 12:24:26,603\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m 2023-04-29 12:24:26,605\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18913)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m 2023-04-29 12:24:26,626\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m 2023-04-29 12:24:26,629\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m 2023-04-29 12:24:26,631\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18916)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m 2023-04-29 12:24:26,620\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m 2023-04-29 12:24:26,623\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m 2023-04-29 12:24:26,626\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18914)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m 2023-04-29 12:24:26,621\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m 2023-04-29 12:24:26,622\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m 2023-04-29 12:24:26,625\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18918)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m 2023-04-29 12:24:26,629\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m 2023-04-29 12:24:26,632\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m 2023-04-29 12:24:26,634\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18917)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n"
     ]
    },
    {
     "ename": "RayTaskError",
     "evalue": "\u001b[36mray::PoolActor.run_batch()\u001b[39m (pid=18920, ip=192.168.86.78)\n  File \"python/ray/_raylet.pyx\", line 493, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 514, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 384, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'TWIG_utils'\ntraceback: Traceback (most recent call last):\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'TWIG_utils'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/kk/ffqddykx5699q_3lb8rnt68h0000gn/T/ipykernel_18879/3626138888.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mstock_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget_ticker_daily_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstock_list\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdate_start\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdate_end\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/projects/west-investment-group/src/TWIG_utils.py\u001b[0m in \u001b[0;36mget_ticker_daily_data\u001b[0;34m(client, ticker, start, end)\u001b[0m\n\u001b[1;32m     61\u001b[0m     \u001b[0;31m# Use map() to parallelize the function calls\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mPool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpool\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m          \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpool\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mget_ticker_data\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minput_data\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;31m# Collect the results and remove any None values\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mmap\u001b[0;34m(self, func, iterable, chunksize)\u001b[0m\n\u001b[1;32m    707\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    708\u001b[0m         return self._map_async(\n\u001b[0;32m--> 709\u001b[0;31m             func, iterable, chunksize=chunksize, unpack_args=False).get()\n\u001b[0m\u001b[1;32m    710\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    711\u001b[0m     def map_async(self,\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    274\u001b[0m                     \u001b[0;32mraise\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munderlying\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    275\u001b[0m                 \u001b[0;32melif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 276\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    277\u001b[0m             \u001b[0mresults\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mextend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbatch\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    278\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m             \u001b[0;34m[\u001b[0m\u001b[0mready_id\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0munready\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0munready\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_returns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    202\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 203\u001b[0;31m                 \u001b[0mbatch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mready_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    204\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mRayError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    205\u001b[0m                 \u001b[0mbatch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     80\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mclient_mode_should_convert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mray\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 82\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     83\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     84\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/worker.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   1562\u001b[0m                     \u001b[0mworker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore_worker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdump_object_store_memory_usage\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1563\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mRayTaskError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1564\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_instanceof_cause\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1565\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1566\u001b[0m                     \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRayTaskError\u001b[0m: \u001b[36mray::PoolActor.run_batch()\u001b[39m (pid=18920, ip=192.168.86.78)\n  File \"python/ray/_raylet.pyx\", line 493, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 514, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 384, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'TWIG_utils'\ntraceback: Traceback (most recent call last):\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'TWIG_utils'"
     ]
    }
   ],
   "source": [
    "stock_data = get_ticker_daily_data(client, stock_list[0], date_start, date_end)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c39d14c1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>open</th>\n",
       "      <th>close</th>\n",
       "      <th>high</th>\n",
       "      <th>low</th>\n",
       "      <th>ticker</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [date, open, close, high, low, ticker]\n",
       "Index: []"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stock_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cb049dde",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "02ec8137",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "environ{'TERM_PROGRAM': 'Apple_Terminal',\n",
       "        'SHELL': '/bin/bash',\n",
       "        'TERM': 'xterm-color',\n",
       "        'TMPDIR': '/var/folders/kk/ffqddykx5699q_3lb8rnt68h0000gn/T/',\n",
       "        'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.nfYBsCtxOi/Render',\n",
       "        'TERM_PROGRAM_VERSION': '421.2',\n",
       "        'OLDPWD': '/Users/adampetranovich/projects/west-investment-group',\n",
       "        'TERM_SESSION_ID': '70FC32D7-CBAF-4CF2-95B5-302407D7BB0C',\n",
       "        'USER': 'adampetranovich',\n",
       "        'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.A5pvJKLc2T/Listeners',\n",
       "        'VIRTUAL_ENV': '/Users/adampetranovich/projects/twigINV',\n",
       "        'PATH': '/Users/adampetranovich/projects/twigINV/bin:/Users/adampetranovich/Library/Python/3.7/bin:/Users/adampetranovich/usr/bin/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki',\n",
       "        'PWD': '/Users/adampetranovich/projects/west-investment-group/notebooks',\n",
       "        'LANG': 'en_US.UTF-8',\n",
       "        'XPC_FLAGS': '0x0',\n",
       "        'PS1': '(twigINV) \\\\h:\\\\W \\\\u\\\\$ ',\n",
       "        'XPC_SERVICE_NAME': '0',\n",
       "        'SHLVL': '1',\n",
       "        'HOME': '/Users/adampetranovich',\n",
       "        'LOGNAME': 'adampetranovich',\n",
       "        '_': '/Users/adampetranovich/projects/twigINV/bin/jupyter-notebook',\n",
       "        '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0',\n",
       "        'PYDEVD_USE_FRAME_EVAL': 'NO',\n",
       "        'JPY_PARENT_PID': '18868',\n",
       "        'CLICOLOR': '1',\n",
       "        'PAGER': 'cat',\n",
       "        'GIT_PAGER': 'cat',\n",
       "        'MPLBACKEND': 'module://matplotlib_inline.backend_inline',\n",
       "        'OMP_NUM_THREADS': '1',\n",
       "        'RAY_CLIENT_MODE': '0',\n",
       "        'KMP_INIT_AT_FORK': 'FALSE'}"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.environ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53917bc4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
