{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7bd86690",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append('../src/')\n",
    "from TWIG_utils import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2ea8785a",
   "metadata": {},
   "outputs": [],
   "source": [
    "stock_list = ['AMZN', 'TSLA', 'SNAP', 'INTC', 'PINS', 'SOFI', 'APPLE', 'F', 'BAC', 'T', 'GOOGL']\n",
    "date_start = '2022-01-01'\n",
    "date_end = '2023-04-28'\n",
    "\n",
    "client = RESTClient(auth_key=\"JeeOjlOPBe5aTiQ_Jb39raRqlam45uAO\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "cc8448a0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting data pull for AMZN...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m 2023-04-29 12:15:29,980\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m 2023-04-29 12:15:29,978\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m 2023-04-29 12:15:29,980\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m 2023-04-29 12:15:29,979\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m 2023-04-29 12:15:29,982\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m 2023-04-29 12:15:29,983\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m 2023-04-29 12:15:29,982\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m 2023-04-29 12:15:29,983\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m 2023-04-29 12:15:30,752\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m 2023-04-29 12:15:30,754\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m 2023-04-29 12:15:30,756\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18509)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m 2023-04-29 12:15:30,752\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m 2023-04-29 12:15:30,754\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m 2023-04-29 12:15:30,756\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18507)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m 2023-04-29 12:15:30,816\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m 2023-04-29 12:15:30,819\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m 2023-04-29 12:15:30,821\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18506)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m 2023-04-29 12:15:30,833\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m 2023-04-29 12:15:30,834\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m 2023-04-29 12:15:30,836\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18508)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m 2023-04-29 12:15:30,842\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m 2023-04-29 12:15:30,845\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m 2023-04-29 12:15:30,847\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18504)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m 2023-04-29 12:15:30,856\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m 2023-04-29 12:15:30,858\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m 2023-04-29 12:15:30,860\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18505)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m 2023-04-29 12:15:30,809\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m 2023-04-29 12:15:30,811\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m 2023-04-29 12:15:30,813\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18503)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m 2023-04-29 12:15:30,863\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m 2023-04-29 12:15:30,865\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m 2023-04-29 12:15:30,867\tERROR serialization.py:253 -- No module named 'TWIG_utils'\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m   File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(pid=18510)\u001b[0m ModuleNotFoundError: No module named 'TWIG_utils'\n"
     ]
    },
    {
     "ename": "RayTaskError",
     "evalue": "\u001b[36mray::PoolActor.run_batch()\u001b[39m (pid=18509, ip=192.168.86.78)\n  File \"python/ray/_raylet.pyx\", line 493, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 514, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 384, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'TWIG_utils'\ntraceback: Traceback (most recent call last):\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'TWIG_utils'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/kk/ffqddykx5699q_3lb8rnt68h0000gn/T/ipykernel_17808/3626138888.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mstock_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget_ticker_daily_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstock_list\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdate_start\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdate_end\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/projects/west-investment-group/src/TWIG_utils.py\u001b[0m in \u001b[0;36mget_ticker_daily_data\u001b[0;34m(client, ticker, start, end)\u001b[0m\n\u001b[1;32m     58\u001b[0m     \u001b[0;31m# Use map() to parallelize the function calls\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     59\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mPool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpool\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 60\u001b[0;31m          \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpool\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mget_ticker_data\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minput_data\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     61\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m     \u001b[0;31m# Collect the results and remove any None values\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mmap\u001b[0;34m(self, func, iterable, chunksize)\u001b[0m\n\u001b[1;32m    707\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    708\u001b[0m         return self._map_async(\n\u001b[0;32m--> 709\u001b[0;31m             func, iterable, chunksize=chunksize, unpack_args=False).get()\n\u001b[0m\u001b[1;32m    710\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    711\u001b[0m     def map_async(self,\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    274\u001b[0m                     \u001b[0;32mraise\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munderlying\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    275\u001b[0m                 \u001b[0;32melif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 276\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    277\u001b[0m             \u001b[0mresults\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mextend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbatch\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    278\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/util/multiprocessing/pool.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m             \u001b[0;34m[\u001b[0m\u001b[0mready_id\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0munready\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0munready\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_returns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    202\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 203\u001b[0;31m                 \u001b[0mbatch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mready_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    204\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mRayError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    205\u001b[0m                 \u001b[0mbatch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     80\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mclient_mode_should_convert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mray\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 82\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     83\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     84\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/projects/twigINV/lib/python3.7/site-packages/ray/worker.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   1562\u001b[0m                     \u001b[0mworker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore_worker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdump_object_store_memory_usage\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1563\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mRayTaskError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1564\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_instanceof_cause\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1565\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1566\u001b[0m                     \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRayTaskError\u001b[0m: \u001b[36mray::PoolActor.run_batch()\u001b[39m (pid=18509, ip=192.168.86.78)\n  File \"python/ray/_raylet.pyx\", line 493, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 514, in ray._raylet.execute_task\n  File \"python/ray/_raylet.pyx\", line 384, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'TWIG_utils'\ntraceback: Traceback (most recent call last):\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 251, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 189, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 167, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/adampetranovich/projects/twigINV/lib/python3.7/site-packages/ray/serialization.py\", line 157, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'TWIG_utils'"
     ]
    }
   ],
   "source": [
    "stock_data = get_ticker_daily_data(client, stock_list[0], date_start, date_end)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c39d14c1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>open</th>\n",
       "      <th>close</th>\n",
       "      <th>high</th>\n",
       "      <th>low</th>\n",
       "      <th>ticker</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [date, open, close, high, low, ticker]\n",
       "Index: []"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stock_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb049dde",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
